# Default PvpGames Configuration File
General:
    Startup:
        StartupCooldown: 10
        GameStartCooldown: 60
        PlayerThreshold: 1
    Game:
        MaxGameLength: 20
Worlds:
    PvPWorld: pvpworld
    LobbyWorld: world
    