# Default PvpGames Configuration File
General:
    Startup:
        GameStartCooldown: 60
        PlayerThreshold: 1
    Game:
        MaxGameLength: 20
Worlds:
    PvPWorld: pvpworld
    LobbyWorld: world
    LobbySpawnCoordinates:
        x: 0
        y: 128
        z: 0